name: spring app

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: develop
        run: |
            mvn clean
            mkdir - p reports
            
      - name: package
        run: |
           mvn package && ls -ltr
           mv **/*.jar target/app.jar
            
      - name: sonar
        run: |
            mvn compile
            mvn sonar:sonar \
              -Dsonar.projectKey=actions \
              -Dsonar.host.url=https://sonarqube-1749-3725.dc-ig-lib-ga-1589529604-f72ef11f3ab089a8c677044eb28292cd-0000.au-syd.containers.appdomain.cloud \
              -Dsonar.login=1d36b3f65a1e157432c4b582d483db463372f7bb

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
           args: >
             -Dsonar.projectKey=actions
             -Dsonar.projectVersion=1.0
             -Dsonar.sources=src/main/java
             -Dsonar.sourceEncoding=UTF-8
             -Dsonar.language=java
             -Dsonar.java.binaries=target/classes
             
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: us.icr.io/dc-tools
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: user/app:latest    
          
